// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqsvllpakgyrwsdulukd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxc3ZsbHBha2d5cndzZHVsdWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2Mzk1ODcsImV4cCI6MjA3MDIxNTU4N30.rldZiCoypb45A2I6TJXXK198U03QmblQE4jY9LY_nFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});